# Generated by Django 5.1 on 2024-08-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('date_born', models.DateField()),
                ('position', models.CharField(choices=[('GO', 'Goleiro'), ('ZG', 'Zagueiro'), ('LD', 'Lateral Direito'), ('LE', 'Lateral Esquerdo'), ('VOL', 'Volante'), ('MC', 'Meio Campo'), ('AT', 'Atacante')], default='GO', max_length=3)),
                ('dominant_leg', models.CharField(choices=[('D', 'Direita'), ('E', 'Esquerda'), ('A', 'Ambas')], default='', max_length=1)),
                ('epecialty', models.CharField(max_length=100)),
            ],
        ),
    ]
