# Generated by Django 5.1 on 2024-08-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_firstname_player_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='epecialty',
            new_name='specialty',
        ),
    ]
